Status
shaynemei/Deadline pull request #17
Opened 2020-08-27 13:22 UTC by yangevelyn

Status page functionality:
 - display nickname, group name
 - display tasks (sorted by completion)
 - add tasks
 - button for task completion

2020-08-27 17:05 UTC, labib666 approved these changes
LGTM!

2020-08-28 10:45 UTC, shaynemei requested changes
Left some comments!

2020-08-28 10:45 UTC, shaynemei commented on webapp/status_server.py
> +    key = db.child('groups').child(group).child(uid).child('tasks').push({
maybe we want to change this to users -> uid -> tasks?
(and other queries for tasks)

2020-08-28 10:45 UTC, shaynemei commented on webapp/status_server.py
> +  print(all_tasks.val())
let's remove all print statements

2020-08-28 10:45 UTC, shaynemei commented on webapp/auth_server.py
> +            'tasks': {}
Do we need to store tasks under groups?

2020-08-28 10:45 UTC, shaynemei commented on webapp/auth_server.py
> +def add_user(email, id, name, group, join):
we might want to init resources -> water, food, metal for non-joining users. Maybe we can start with 20 units each?

2020-08-29 14:24 UTC, shaynemei approved these changes
LGTM!

2020-08-29 14:25 UTC, merged